#!/bin/bash

# Find the line in "xrandr -q --verbose" output that contains current screen orientation and "strip" out current orientation.

rotation="$(xrandr -q --verbose | grep 'connected' | egrep -o  '\) (normal|left|inverted|right) \(' | egrep -o '(normal|left|inverted|right)')"

# Using current screen orientation proceed to rotate screen and input devices.

case "$rotation" in
    normal)
    # rotate to the left
    xrandr -o inverted
    xsetwacom set "IPTS Stylus stylus" rotate half
    xsetwacom set "IPTS Stylus eraser" rotate half
    xsetwacom set "IPTS Touch touch" rotate half
    ;;
    inverted)
    # rotate to the right
    xrandr -o normal
    xsetwacom set "IPTS Stylus stylus" rotate none
    xsetwacom set "IPTS Stylus eraser" rotate none
    xsetwacom set "IPTS Touch touch" rotate none
    ;;
esac

