#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

# Load and execute custom profiles
if [ -d ~/.profile ] ; then
    if [ -f ~/.profile/xprofile ] ; then
        source ~/.profile/xprofile
    fi
fi

sh $HOME/.scripts/updateBackground.sh &                       # Update LightDM background (delay of 5min)

exec i3 & wmpid=$!

sleep 5
$HOME/.scripts/updateLoginBackground.sh                       # Update LightDM background (delay of 5min)

wait $wmpid
