#!/bin/sh

# --------------------------------------------
# Actions / exports when bash gets loaded
# --------------------------------------------
export DOTNET_CLI_TELEMETRY_OPTOUT=1                                        # Opt out of dotnet telemtry
(cat ~/.cache/wal/sequences &)

if test -f ~/.ssh/id_rsa
then
    eval $(keychain --eval --quiet id_rsa)                                  # Initializes the keychain
fi

# Setup the gpg agent
export GPG_TTY="$(tty)"
export SSH_AUTH_SOCK=$(gpgconf --list-dirs agent-ssh-socket)
gpgconf --launch gpg-agent

(wal -R -e -n -q &)                                                        # Reload pywal theme

# Turn off screensaver
export DISPLAY=:0.0
xset s off
xset s noblank
xset -dpms

export PATH="$PATH:~/.dotnet/tools"
