#!/bin/sh

# --------------------------------------------
# Actions / exports when bash gets loaded
# --------------------------------------------
export DOTNET_CLI_TELEMETRY_OPTOUT=1                                        # Opt out of dotnet telemtry
alias nuget="mono /usr/local/bin/nuget.exe"                                 # Add mono nuget call to bin so nuget packaging CLI works
eval $(keychain --eval --quiet id_rsa)                                      # Initializes the keychain
