#!/bin/sh

# --------------------------------------------
# Actions / exports when X11 is initialized
# --------------------------------------------
#
# --------------------------------------------
# Surface book HiDPI and input settings
# --------------------------------------------

export GDK_SCALE=1                                      # Set GDK_SCALE to 2 to enable HiDPI support in GDK applications
#export QT_SCALE_FACTOR=1                                # Set QT scaling to 2 to enable HiDPI support in QT applications
export display=:0                                       # Set default display
export MSBuildSDKsPath=/opt/dotnet/sdk/$(dotnet --version)/Sdks

setxkbmap ch -variant de                                # Set keyboard mapping to ch-de