#!/bin/sh
# --------------------------------------------
# Actions / exports when bash gets loaded
# --------------------------------------------

export DOTNET_CLI_TELEMETRY_OPTOUT=1                                        # Opt out of dotnet telemtry
alias spotify="/usr/bin/spotify --force-device-scale-factor=2.0"
(wal -R -e -q -n &)                                                            # Reload pywal theme
eval $(keychain --eval --quiet id_rsa)                                      # Initializes the keychain