#!/bin/sh
# --------------------------------------------
# Actions / exports when bash gets loaded
# --------------------------------------------

export DOTNET_CLI_TELEMETRY_OPTOUT=1 # Opt out of dotnet telemtry
alias spotify="/usr/bin/spotify --force-device-scale-factor=2.0"
(wal -R -e -q -n &)                    # Reload pywal theme
if test -f ~/.ssh/id_rsa
then
    eval $(keychain --eval --quiet id_rsa)                                  # Initializes the keychain
fi

# Setup the gpg agent
export GPG_TTY="$(tty)"
export SSH_AUTH_SOCK=$(gpgconf --list-dirs agent-ssh-socket)
gpgconf --launch gpg-agent

# Turn off screensaver
export DISPLAY=:0.0
xset s off
xset s noblank
