#!/bin/sh

# --------------------------------------------
# Actions / exports when bash gets loaded
# --------------------------------------------

export DOTNET_CLI_TELEMETRY_OPTOUT=1            # Opt out of dotnet telemtry
export DOTNET_ROOT=/opt/dotnet
export MSBuildSDKsPath=$DOTNET_ROOT/sdk/$(${DOTNET_ROOT}/dotnet --version)/Sdks
export PATH=${PATH}:${DOTNET_ROOT}

alias nuget="mono /usr/local/bin/nuget.exe"     # Add mono nuget call to bin so nuget packaging CLI works

