#!/bin/sh

export EDITOR=nvim
(wal -R -e -n -q &)                                                         # Reload pywal theme

eval $(keychain --eval --quiet id_rsa)                                      # Initializes the keychain
