#!/bin/sh

# --------------------------------------------
# Actions / exports when bash gets loaded
# --------------------------------------------
export DOTNET_CLI_TELEMETRY_OPTOUT=1                                        # Opt out of dotnet telemtry

(wal -R -e -n -q &)                                                         # Reload pywal theme

eval $(keychain --eval --quiet id_rsa)                                      # Initializes the keychain