#!/bin/sh

# --------------------------------------------
# Actions / exports when X11 is initialized
# --------------------------------------------
#
# --------------------------------------------
# Surface book HiDPI and input settings
# --------------------------------------------
export display=:1                                       # Set default display
export MSBuildSDKsPath=/opt/dotnet/sdk/$(dotnet --version)/Sdks

setxkbmap ch -variant de                                # Set keyboard mapping to ch-de