#!/bin/sh

# --------------------------------------------
# Actions / exports when X11 is initialized
# --------------------------------------------
export EDITOR=nvim
export display=:1                                       # Set default display

setxkbmap ch -variant de                                # Set keyboard mapping to ch-de

# Download new background photo
sh ~/.scripts/updateLoginBackground.sh &

# Set screen layout
sh ~/.screenlayout/3-screens.sh
